apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-ssl-cert
  namespace: metabase
  labels:
    app: metabase-app
    component: postgres-ssl
data:
  server-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDfzCCAmegAwIBAgIBADANBgkqhkiG9w0BAQsFADB3MS0wKwYDVQQuEyQ3ZmVh
    NjUzNC1lYzllLTRkMDAtYjYzYi1lYjNlMGI5YjIwNTgxIzAhBgNVBAMTGkdvb2ds
    ZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkG
    A1UEBhMCVVMwHhcNMjUwNTIwMTI0NDQ3WhcNMzUwNTE4MTI0NTQ3WjB3MS0wKwYD
    VQQuEyQ3ZmVhNjUzNC1lYzllLTRkMDAtYjYzYi1lYjNlMGI5YjIwNTgxIzAhBgNV
    BAMTGkdvb2dsZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUs
    IEluYzELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQCz3BLS6gsotU0kjKByMvWS8lfz900GAFnUXqFJLOOBYJS6args/mk7Hi9qBSCU
    +m4YTVKdlVWmBcwPGOmCV4cYs3xmRX1sqFvwk8hM/tccJTpgMd6DmubJC8zfKD6J
    2XXKgWSMD0ifGhCWxAK+vmHK62bCXIpOGVRRJo1o6o9vtFojiB3i0skUdWIxOnM9
    k+WWoVt/GXWQQctzSIPHwPe8n2vHZWuu3qlxfI8jnWLKL8/xEc/G/TSEh9bNyav3
    G6JuA9VHwGt+OmS3UtrJjeYUnbxd4MGQg1UGbSKYz4IBrDN83fv8+Yyrt5yCfnMI
    XyxcvN6Io6mkr4l60SJAMt47AgMBAAGjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQAw
    DQYJKoZIhvcNAQELBQADggEBAJbbkxS4LB0zjZtm93f7rfCAh5O5MwAdZtywN12p
    vygne9AUFVuQavMGF+9DmvAsz+b382gZ/3FMTL1s8C3wwdPyTyBAweCQhov1dD8e
    CyP5eIShY03tXUJzCwjJSAkDJ0JVN+G4JR4G5JBe23JWZd8YzZ+vxHzR/J1P8xQF
    RueMBygt3SgQ0861bB8EE1b7duWxG0WzKA7MIJoxdWk76Mu5Rn39PHYSunjkO1js
    7D8aX4/vk0fLYPifWI+tVY7KX/hFH6bD03wC4jLSb4P5E4nrvZ5OzbxFc2+LArls
    PywWGqQn7L3cEz8gphg+y1mbPkmJ+jO3AwS7K1uf5XWJuDc=
    -----END CERTIFICATE-----




